server:
  port: 9991

kafka:
  bootstrapAddress: localhost:1234
  subscribeTopic: products

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  datasource:
    url: "jdbc:sqlserver://localhost:3333;databaseName=productsdb;encrypt=true;trustServerCertificate=true;"
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Sg.0s5+39?D)
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      ddl-auto: update
    show-sql: true
