server:
  port: 8881

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

kafka:
  bootstrapAddress: localhost:1234
