server:
  port: 8881

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

kafka:
  bootstrapAddress: localhost:1234
  topics:
    product: product
    list: listOfProducts
  producer:
    retries: 1
    batch-size: 16384
    linger-ms: 0
    buffer-memory: 33554432
    max-block-ms: 5000
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
    enable-auto-commit: false
    auto-commit-interval-ms: 100
    session-timeout-ms: 15000
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    group-id: productManagementWebApp
    auto-offset-reset: latest
