server:
  port: 9991

kafka:
  bootstrapAddress: localhost:1234
  topics:
    product: product
    list: listOfProducts
  consumer:
    enable-auto-commit: false
    auto-commit-interval-ms: 100
    session-timeout-ms: 15000
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    group-id: productDb
    auto-offset-reset: earliest
  producer:
    retries: 0
    batch-size: 16384
    linger-ms: 1
    buffer-memory: 33554432
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  datasource:
    url: "jdbc:sqlserver://localhost:3333;databaseName=productsdb;encrypt=true;trustServerCertificate=true;"
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Sg.0s5+39?D)
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      ddl-auto: update
    show-sql: true
